package ie.droidfactory.irishrails.model;

/**
 * Created by kudlaty on 26/09/2017.
 */

public enum Cities {

    _109    ("Dublin", "Clontarf Road", "http://www.irishrail.ie/travel-information/clontarf-road"),
    _101    ("Dublin", "Killester", "http://www.irishrail.ie/travel-information/killester"),
    _99     ("Dublin", "Drumcondra", "http://www.irishrail.ie/travel-information/drumcondra"),
    _102    ("Dublin", "Harmonstown", "http://www.irishrail.ie/travel-information/harmonstown"),
    _100    ("Dublin", "Dublin Connolly", "http://www.irishrail.ie/travel-information/dublin-connolly"),
    _84     ("Dublin", "Docklands", "http://www.irishrail.ie/travel-information/docklands"),
    _103    ("Dublin", "Raheny", "http://www.irishrail.ie/travel-information/raheny"),
    _124    ("Dublin", "Tara Street", "http://www.irishrail.ie/travel-information/tara-street"),
    _150    ("Dublin", "Dublin Pearse", "http://www.irishrail.ie/travel-information/dublin-pearse"),
    _98     ("Dublin", "Broombridge", "http://www.irishrail.ie/travel-information/broombridge"),
    _110    ("Dublin", "Grand Canal Dock", "http://www.irishrail.ie/travel-information/grand-canal-dock"),
    _104    ("Dublin", "Kilbarrack", "http://www.irishrail.ie/travel-information/kilbarrack"),
    _125    ("Dublin", "Lansdowne Road", "http://www.irishrail.ie/travel-information/lansdowne-road"),
    _105    ("Dublin", "Howth Junction", "http://www.irishrail.ie/travel-information/howth-junction-and-donaghmede"),
    _1      ("Dublin", "Dublin Heuston", "http://www.irishrail.ie/travel-information/dublin-heuston"),
    _188    ("Dublin", "Sandymount", "http://www.irishrail.ie/travel-information/sandymount"),
    _187    ("Dublin", "Clongriffin", "http://www.irishrail.ie/travel-information/clongriffin"),
    _106    ("Dublin","Bayside", "http://www.irishrail.ie/travel-information/bayside"),
    _97     ("Dublin", "Ashtown", "http://www.irishrail.ie/travel-information/ashtown"),
    _111    ("Dublin", "Portmarnock", "http://www.irishrail.ie/travel-information/portmarnock"),
    _126    ("Dublin", "Sydney Parade", "http://www.irishrail.ie/travel-information/sydney-parade"),
    _89     ("Dublin", "Navan Road Parkway", "http://www.irishrail.ie/travel-information/navan-road-parkway"),
    _107    ("Dublin", "Sutton", "http://www.irishrail.ie/travel-information/sutton"),
    _127    ("Dublin", "Booterstown", "http://www.irishrail.ie/travel-information/booterstown"),
    _96     ("Dublin", "Castleknock", "http://www.irishrail.ie/travel-information/castleknock"),
    _112    ("Dublin", "Malahide", "http://www.irishrail.ie/travel-information/malahide"),
    _128    ("Dublin", "Blackrock", "http://www.irishrail.ie/travel-information/blackrock"),
    _129    ("Dublin", "Seapoint", "http://www.irishrail.ie/travel-information/seapoint"),
    _95     ("Dublin", "Coolmine", "http://www.irishrail.ie/travel-information/coolmine"),
    _108    ("Dublin", "Howth", "http://www.irishrail.ie/travel-information/howth"),
    _130    ("Dublin", "Salthill", "http://www.irishrail.ie/travel-information/salthill-and-monkstown"),
    _1076   ("Dublin", "PARK WEST", null),
    _976    ("Dublin", "Cherry Orchard", null),
    _76     ("Dublin", "Cherry Orchard", "http://www.irishrail.ie/travel-information/park-west-and-cherry-orchard"),
    _131    ("Dublin", "Dun Laoghaire", "http://www.irishrail.ie/travel-information/dun-laoghaire-mallin"),
    _132    ("Dublin", "Sandycove", "http://www.irishrail.ie/travel-information/sandycove-and-glasthule"),
    _1077   ("Dublin", "Clondalkin", null),
    _77     ("Dublin", "Clondalkin", "http://www.irishrail.ie/travel-information/clondalkin-fonthill"),
    _977    ("Dublin", "Clondalkin", null),
    _94     ("Dublin", "Clonsilla", "http://www.irishrail.ie/travel-information/clonsilla"),
    _113    ("Dublin", "Donabate", "http://www.irishrail.ie/travel-information/donabate"),
    _133    ("Dublin", "Glenageary", "http://www.irishrail.ie/travel-information/glenageary"),
    _87     ("Dublin", "Hansfield", "http://www.irishrail.ie/travel-information/hansfield"),
    _134    ("Dublin", "Dalkey", "http://www.irishrail.ie/travel-information/dalkey"),
    _975    ("Dublin", "Adamstown", "http://www.irishrail.ie/travel-information/adamstown"),
    _75     ("Dublin", "Adamstown", "http://www.irishrail.ie/travel-information/adamstown"),
    _85     ("Dublin", "Dunboyne", "http://www.irishrail.ie/travel-information/dunboyne"),
    _135    ("Dublin", "Killiney", "http://www.irishrail.ie/travel-information/killiney"),
    _114    ("Dublin", "Rush and Lusk", "http://www.irishrail.ie/travel-information/rush-and-lusk"),
    _86     ("Dublin", "M3 Parkway", "http://www.irishrail.ie/travel-information/m3-parkway"),
    _93     ("Dublin", "Leixlip (Confey)", "http://www.irishrail.ie/travel-information/leixlip-confey"),
    _136    ("Dublin", "Shankill", "http://www.irishrail.ie/travel-information/shankill"),
    _92     ("Dublin", "Leixlip (Louisa Bridge)", "http://www.irishrail.ie/travel-information/leixlip-louisa-bridge"),
    _801    ("Dublin", "Woodbrook", null),
    _1078   ("Dublin", "Hazelhatch", null),
    _978    ("Dublin", "Hazelhatch", null),
    _78     ("Dublin", "Hazelhatch", "http://www.irishrail.ie/travel-information/hazelhatch-and-celbridge"),
    _140    ("Dublin", "Bray", "http://www.irishrail.ie/travel-information/bray-daly"),
    _115    ("", "Skerries", "http://www.irishrail.ie/travel-information/skerries"),
    _91     ("", "Maynooth", "http://www.irishrail.ie/travel-information/maynooth"),
    _116    ("", "Balbriggan", "http://www.irishrail.ie/travel-information/balbriggan"),
    _117    ("", "Gormanston", "http://www.irishrail.ie/travel-information/gormanston"),
    _141    ("", "Greystones", "http://www.irishrail.ie/travel-information/greystones"),
    _90     ("", "Kilcock", "http://www.irishrail.ie/travel-information/kilcock"),
    _79     ("", "Sallins", "http://www.irishrail.ie/travel-information/sallins-and-naas"),
    _139    ("", "Kilcoole", "http://www.irishrail.ie/travel-information/kilcoole"),
    _119    ("", "Laytown", "http://www.irishrail.ie/travel-information/laytown"),
    _120    ("", "Drogheda", "http://www.irishrail.ie/travel-information/drogheda-macbride"),
    _83     ("Station Yard", "Enfield", "http://www.irishrail.ie/travel-information/enfield"),
    _4      ("", "Newbridge", "http://www.irishrail.ie/travel-information/newbridge"),
    _142    ("", "Wicklow", "http://www.irishrail.ie/travel-information/wicklow"),
    _5      ("", "Curragh", null),
    _143    ("", "Rathdrum", "http://www.irishrail.ie/travel-information/rathdrum"),
    _6      ("", "Kildare", "http://www.irishrail.ie/travel-information/kildare"),
    _1075   ("", "Adamstown", null),
    _7      ("", "Monasterevin", "http://www.irishrail.ie/travel-information/monasterevin"),
    _144    ("", "Arklow", "http://www.irishrail.ie/travel-information/arklow"),
    _45     ("", "Athy", "http://www.irishrail.ie/travel-information/athy"),
    _8      ("", "Portarlington", "http://www.irishrail.ie/travel-information/portarlington"),
    _123    ("", "Dundalk", "http://www.irishrail.ie/travel-information/dundalk-clarke"),
    _153    ("", "Mullingar", "http://www.irishrail.ie/travel-information/mullingar"),
    _46     ("", "Carlow", "http://www.irishrail.ie/travel-information/carlow"),
    _145    ("", "Gorey", "http://www.irishrail.ie/travel-information/gorey"),
    _9      ("", "Portlaoise", "http://www.irishrail.ie/travel-information/portlaoise"),
    _72     ("", "Tullamore", "http://www.irishrail.ie/travel-information/tullamore"),
    _47     ("", "Muine Bheag", "http://www.irishrail.ie/travel-information/muine-bheag-bagenalstown"),
    _260    ("", "Newry", "http://www.irishrail.ie/travel-information/newry"),
    _73     ("", "Clara", "http://www.irishrail.ie/travel-information/clara"),
    _171    ("", "Edgeworthstown", "http://www.irishrail.ie/travel-information/edgeworthstown"),
    _147    ("", "Enniscorthy", "http://www.irishrail.ie/travel-information/enniscorthy"),
    _48     ("", "Kilkenny", "http://www.irishrail.ie/travel-information/kilkenny-macdonagh"),
    _11     ("", "Ballybrophy", "http://www.irishrail.ie/travel-information/ballybrophy"),
    _172    ("", "Longford", "http://www.irishrail.ie/travel-information/longford"),
    _156    ("", "Athlone", "http://www.irishrail.ie/travel-information/athlone"),
    _49     ("", "Thomastown", "http://www.irishrail.ie/travel-information/thomastown"),
    _31     ("", "Roscrea", "http://www.irishrail.ie/travel-information/roscrea"),
    _148    ("", "Wexford", "http://www.irishrail.ie/travel-information/wexford-o-hanrahan"),
    _242    ("", "Portadown", "http://www.irishrail.ie/travel-information/portadown"),
    _241    ("", "Lurgan", "http://www.irishrail.ie/travel-information/lurgan"),
    _173    ("", "Drumod", "http://www.irishrail.ie/travel-information/dromod"),
    _58     ("", "Rosslare Strand", "http://www.irishrail.ie/travel-information/rosslare-strand"),
    _12     ("", "Templemore", "http://www.irishrail.ie/travel-information/templemore"),
    _60     ("", "Rosslare Harbour Europort", "http://www.irishrail.ie/travel-information/rosslare-europort"),
    _238    ("", "Lisburn", "http://www.irishrail.ie/travel-information/lisburn"),
    _54     ("", "Wellingtonbridge", null),
    _53     ("", "Ballycullane", null),
    _32     ("", "Cloughjordan", "http://www.irishrail.ie/travel-information/cloughjordan"),
    _56     ("", "Bridgetown", null),
    _52     ("", "Campile", null),
    _13     ("", "Thurles", "http://www.irishrail.ie/travel-information/thurles"),
    _163    ("", "Roscommon", "http://www.irishrail.ie/travel-information/roscommon"),
    _157    ("", "Ballinasloe", "http://www.irishrail.ie/travel-information/ballinasloe"),
    _50     ("", "Waterford", "http://www.irishrail.ie/travel-information/waterford-plunkett"),
    _174    ("", "Carrick on Shannon", "http://www.irishrail.ie/travel-information/carrickonshannon"),
    _228    ("", "Belfast Central", "http://www.irishrail.ie/travel-information/belfast-central"),
    _44     ("", "Carrick on Suir", "http://www.irishrail.ie/travel-information/carrickonsuir"),
    _33     ("", "Nenagh", "http://www.irishrail.ie/travel-information/nenagh"),
    _158    ("", "Woodlawn", "http://www.irishrail.ie/travel-information/woodlawn"),
    _43     ("", "Clonmel", "http://www.irishrail.ie/travel-information/clonmel"),
    _175    ("", "Boyle", "http://www.irishrail.ie/travel-information/boyle"),
    _164    ("", "Castlerea", "http://www.irishrail.ie/travel-information/castlerea"),
    _159    ("", "Attymon", "http://www.irishrail.ie/travel-information/attymon"),
    _42     ("", "Cahir", "http://www.irishrail.ie/travel-information/cahir"),
    _34     ("", "Birdhill", "http://www.irishrail.ie/travel-information/birdhill"),
    _16     ("", "Limerick Junction", "http://www.irishrail.ie/travel-information/limerick-junction"),
    _41     ("", "Tipperary", "http://www.irishrail.ie/travel-information/tipperary"),
    _184    ("", "Craughwell", "http://www.irishrail.ie/travel-information/craughwell"),
    _162    ("", "Athenry", "http://www.irishrail.ie/travel-information/athenry"),
    _35     ("", "Castleconnell", "http://www.irishrail.ie/travel-information/castleconnell"),
    _176    ("", "Ballymote", "http://www.irishrail.ie/travel-information/ballymote"),
    _165    ("", "Ballyhaunis", "http://www.irishrail.ie/travel-information/ballyhaunis"),
    _177    ("", "Collooney", "http://www.irishrail.ie/travel-information/collooney"),
    _183    ("", "Ardrahan", "http://www.irishrail.ie/travel-information/ardrahan"),
    _182    ("", "Gort", "http://www.irishrail.ie/travel-information/gort"),
    _180    ("", "Sligo", "http://www.irishrail.ie/travel-information/sligo-macdiarmada"),
    _40     ("", "Limerick", "http://www.irishrail.ie/travel-information/limerick-colbert"),
    _161    ("", "Oranmore", "http://www.irishrail.ie/travel-information/oranmore"),
    _185    ("", "Sixmilebridge", "http://www.irishrail.ie/travel-information/sixmilebridge"),
    _166    ("", "Claremorris", "http://www.irishrail.ie/travel-information/claremorris"),
    _170    ("", "Galway", "http://www.irishrail.ie/travel-information/galway-ceannt"),
    _181    ("", "Ennis", "http://www.irishrail.ie/travel-information/ennis"),
    _19     ("", "Charleville", "http://www.irishrail.ie/travel-information/charleville"),
    _194    ("", "Manulla Junction", "http://www.irishrail.ie/travel-information/manulla-junction"),
    _193    ("", "Foxford", "http://www.irishrail.ie/travel-information/foxford"),
    _168    ("", "Castlebar", "http://www.irishrail.ie/travel-information/castlebar"),
    _68     ("", "Midleton", "http://www.irishrail.ie/travel-information/midleton"),
    _167    ("", "Ballina", "http://www.irishrail.ie/travel-information/ballina"),
    _67     ("", "Carrigtwohill", "http://www.irishrail.ie/travel-information/carrigtwohill"),
    _21     ("", "Mallow", "http://www.irishrail.ie/travel-information/mallow"),
    _380    ("", "Glounthaune", "http://www.irishrail.ie/travel-information/glounthaune"),
    _63     ("", "Fota", "http://www.irishrail.ie/travel-information/fota"),
    _61     ("", "LittleIsland", "http://www.irishrail.ie/travel-information/little-island"),
    _64     ("", "Carrigaloe", "http://www.irishrail.ie/travel-information/carrigaloe"),
    _66     ("", "Cobh", "http://www.irishrail.ie/travel-information/cobh"),
    _65     ("", "Rushbrooke", "http://www.irishrail.ie/travel-information/rushbrooke"),
    _169    ("", "Westport", "http://www.irishrail.ie/travel-information/westport"),
    _30     ("", "Cork", "http://www.irishrail.ie/travel-information/cork-kent"),
    _23     ("", "Banteer", "http://www.irishrail.ie/travel-information/banteer"),
    _24     ("", "Millstreet", "http://www.irishrail.ie/travel-information/millstreet"),
    _25     ("", "Rathmore", "http://www.irishrail.ie/travel-information/rathmore"),
    _27     ("", "Farranfore", "http://www.irishrail.ie/travel-information/farranfore"),
    _28     ("", "Tralee", "http://www.irishrail.ie/travel-information/tralee-casement"),
    _26     ("", "Killarney", "http://www.irishrail.ie/travel-information/killarney"),
    _1517   ("", "CENTRAL JUNCTION", null),
    _1516   ("", "CITY JUNCTION", null),
    _1518   ("", "DUNMURRAY", null),
    _1519   ("", "MOIRA", null);

//    _109    ("Dublin", "Clontarf Road"),
//    _101    ("Dublin", "Killester"),
//    _99     ("Dublin", "Drumcondra"),
//    _102    ("Dublin", "Harmonstown"),
//    _100    ("Dublin", "Dublin Connolly"),
//    _84     ("Dublin", "Docklands"),
//    _103    ("Dublin", "Raheny"),
//    _124    ("Dublin", "Tara Street"),
//    _150    ("Dublin", "Dublin Pearse"),
//    _98     ("Dublin", "Broombridge"),
//    _110    ("Dublin", "Grand Canal Dock"),
//    _104    ("Dublin", "Kilbarrack"),
//    _125    ("Dublin", "Lansdowne Road"),
//    _105    ("Dublin", "Howth Junction"),
//    _1      ("Dublin", "Dublin Heuston"),
//    _188    ("Dublin", "Sandymount"),
//    _187    ("Dublin", "Clongriffin"),
//    _106    ("Dublin","Bayside"),
//    _97     ("Dublin", "Ashtown"),
//    _111    ("Dublin", "Portmarnock"),
//    _126    ("Dublin", "Sydney Parade"),
//    _89     ("Dublin", "Navan Road Parkway"),
//    _107    ("Dublin", "Sutton"),
//    _127    ("Dublin", "Booterstown"),
//    _96     ("Dublin", "Castleknock"),
//    _112    ("Dublin", "Malahide"),
//    _128    ("Dublin", "Blackrock"),
//    _129    ("Dublin", "Seapoint"),
//    _95     ("Dublin", "Coolmine"),
//    _108    ("Dublin", "Howth"),
//    _130    ("Dublin", "Salthill"),
//    _1076   ("Dublin", "PARK WEST"),
//    _976    ("Dublin", "Cherry Orchard"),
//    _76     ("Dublin", "Cherry Orchard"),
//    _131    ("Dublin", "Dun Laoghaire"),
//    _132    ("Dublin", "Sandycove"),
//    _1077   ("Dublin", "Clondalkin"),
//    _77     ("Dublin", "Clondalkin"),
//    _977    ("Dublin", "Clondalkin"),
//    _94     ("Dublin", "Clonsilla"),
//    _113    ("Dublin", "Donabate"),
//    _133    ("Dublin", "Glenageary"),
//    _87     ("Dublin", "Hansfield"),
//    _134    ("Dublin", "Dalkey"),
//    _975    ("Dublin", "Adamstown"),
//    _75     ("Dublin", "Adamstown"),
//    _85     ("Dublin", "Dunboyne"),
//    _135    ("Dublin", "Killiney"),
//    _114    ("Dublin", "Rush and Lusk"),
//    _86     ("Dublin", "M3 Parkway"),
//    _93     ("Dublin", "Leixlip (Confey)"),
//    _136    ("Dublin", "Shankill"),
//    _92     ("Dublin", "Leixlip (Louisa Bridge)"),
//    _801    ("Dublin", "Woodbrook"),
//    _1078   ("Dublin", "Hazelhatch"),
//    _978    ("Dublin", "Hazelhatch"),
//    _78     ("Dublin", "Hazelhatch"),
//    _140    ("Dublin", "Bray"),
//    _115    ("Skerries", "Skerries"),
//    _91     ("Maynooth", "Maynooth"),
//    _116    ("Balbriggan", "Balbriggan"),
//    _117    ("Gormanston", "Gormanston"),
//    _141    ("Greystones", "Greystones"),
//    _90     ("Kilcock", "Kilcock"),
//    _79     ("Sallins", "Sallins"),
//    _139    ("Kilcoole", "Kilcoole"),
//    _119    ("Laytown", "Laytown"),
//    _120    ("Drogheda", "Drogheda"),
//    _83     ("Station Yard", "Enfield"),
//    _4      ("Newbridge", "Newbridge"),
//    _142    ("Wicklow", "Wicklow"),
//    _5      ("Curragh", "Curragh"),
//    _143    ("Rathdrum", "Rathdrum"),
//    _6      ("Kildare", "Kildare"),
//    _1075   ("Adamstown", "Adamstown"),
//    _7      ("Monasterevin", "Monasterevin"),
//    _144    ("Arklow", "Arklow"),
//    _45     ("Athy", "Athy"),
//    _8      ("Portarlington", "Portarlington"),
//    _123    ("Dundalk", "Dundalk"),
//    _153    ("Mullingar", "Mullingar"),
//    _46     ("Carlow", "Carlow"),
//    _145    ("Gorey", "Gorey"),
//    _9      ("Portlaoise","Portlaoise"),
//    _72     ("Tullamore", "Tullamore"),
//    _47     ("Muine Bheag", "Muine Bheag"),
//    _260    ("Newry", "Newry"),
//    _73     ("Clara", "Clara"),
//    _171    ("Edgeworthstown", "Edgeworthstown"),
//    _147    ("Enniscorthy", "Enniscorthy"),
//    _48     ("Kilkenny", "Kilkenny"),
//    _11     ("Ballybrophy","Ballybrophy"),
//    _172    ("Longford", "Longford"),
//    _156    ("Athlone", "Athlone"),
//    _49     ("Thomastown", "Thomastown"),
//    _31     ("Roscrea", "Roscrea"),
//    _148    ("Wexford", "Wexford"),
//    _242    ("Portadown", "Portadown"),
//    _241    ("Lurgan", "Lurgan"),
//    _173    ("Drumod", "Drumod"),
//    _58     ("Rosslare", "Rosslare Strand"),
//    _12     ("Templemore", "Templemore"),
//    _60     ("Rosslare Harbour", "Rosslare Europort"),
//    _238    ("Lisburn", "Lisburn"),
//    _54     ("Wellingtonbridge", "Wellingtonbridge"),
//    _53     ("Ballycullane", "Ballycullane"),
//    _32     ("Cloughjordan", "Cloughjordan"),
//    _56     ("Bridgetown", "Bridgetown"),
//    _52     ("Campile", "Campile"),
//    _13     ("Thurles", "Thurles"),
//    _163    ("Roscommon", "Roscommon"),
//    _157    ("Ballinasloe", "Ballinasloe"),
//    _50     ("Waterford", "Waterford"),
//    _174    ("Carrick on Shannon", "Carrick on Shannon"),
//    _228    ("Belfast", "Belfast Central"),
//    _44     ("Carrick on Suir", "Carrick on Suir"),
//    _33     ("Nenagh", "Nenagh"),
//    _158    ("Woodlawn", "Woodlawn"),
//    _43     ("Clonmel", "Clonmel"),
//    _175    ("Boyle", "Boyle"),
//    _164    ("Castlerea", "Castlerea"),
//    _159    ("Attymon", "Attymon"),
//    _42     ("Cahir", "Cahir"),
//    _34     ("Birdhill", "Birdhill"),
//    _16     ("Limerick Junction", "Limerick Junction"),
//    _41     ("Tipperary", "Tipperary"),
//    _184    ("Craughwell", "Craughwell"),
//    _162    ("Athenry", "Athenry"),
//    _35     ("Castleconnell", "Castleconnell"),
//    _176    ("Ballymote", "Ballymote"),
//    _165    ("Ballyhaunis", "Ballyhaunis"),
//    _177    ("Collooney", "Collooney"),
//    _183    ("Ardrahan", "Ardrahan"),
//    _182    ("Gort", "Gort"),
//    _180    ("Sligo", "Sligo"),
//    _40     ("Limerick", "Limerick"),
//    _161    ("Oranmore", "Oranmore"),
//    _185    ("Sixmilebridge", "Sixmilebridge"),
//    _166    ("Claremorris", "Claremorris"),
//    _170    ("Galway", "Galway"),
//    _181    ("Ennis", "Ennis"),
//    _19     ("Charleville", "Charleville"),
//    _194    ("Manulla", "Manulla Junction"),
//    _193    ("Foxford", "Foxford"),
//    _168    ("Castlebar", "Castlebar"),
//    _68     ("Midleton", "Midleton"),
//    _167    ("Ballina", "Ballina"),
//    _67     ("Carrigtwohill", "Carrigtwohill"),
//    _21     ("Mallow", "Mallow"),
//    _380    ("Glounthaune", "Glounthaune"),
//    _63     ("Fota", "Fota"),
//    _61     ("LittleIsland", "LittleIsland"),
//    _64     ("Carrigaloe", "Carrigaloe"),
//    _66     ("Cobh", "Cobh"),
//    _65     ("Rushbrooke", "Rushbrooke"),
//    _169    ("Westport", "Westport"),
//    _30     ("Cork", "Cork"),
//    _23     ("Banteer", "Banteer"),
//    _24     ("Millstreet", "Millstreet"),
//    _25     ("Rathmore", "Rathmore"),
//    _27     ("Farranfore", "Farranfore"),
//    _28     ("Tralee", "Tralee"),
//    _26     ("Killarney", "Killarney"),
//    _1517   ("CENTRAL JUNCTION", "CENTRAL JUNCTION"),
//    _1516   ("CITY JUNCTION", "CITY JUNCTION"),
//    _1518   ("DUNMURRAY", "DUNMURRAY"),
//    _1519   ("MOIRA", "MOIRA");

    public static final String D = "Dublin";
    String city, name, detailsUrl;
    Cities(String city, String name, String detailsUrl){
        this.city=city;
        this.name = name;
        this.detailsUrl=detailsUrl;
    }

    public String getCity() {
        return city;
    }

    public String getName() {
        return name;
    }

    public String getDetailsUrl() {
        return detailsUrl;
    }
}

