package ie.droidfactory.irishrails.model;

/**
 * Created by kudlaty on 26/09/2017.
 */

public enum Cities {

    _109    ("Dublin", "Clontarf Road"),
    _101    ("Dublin", "Killester"),
    _99     ("Dublin", "Drumcondra"),
    _102    ("Dublin", "Harmonstown"),
    _100    ("Dublin", "Dublin Connolly"),
    _84     ("Dublin", "Docklands"),
    _103    ("Dublin", "Raheny"),
    _124    ("Dublin", "Tara Street"),
    _150    ("Dublin", "Dublin Pearse"),
    _98     ("Dublin", "Broombridge"),
    _110    ("Dublin", "Grand Canal Dock"),
    _104    ("Dublin", "Kilbarrack"),
    _125    ("Dublin", "Lansdowne Road"),
    _105    ("Dublin", "Howth Junction"),
    _1      ("Dublin", "Dublin Heuston"),
    _188    ("Dublin", "Sandymount"),
    _187    ("Dublin", "Clongriffin"),
    _106    ("Dublin","Bayside"),
    _97     ("Dublin", "Ashtown"),
    _111    ("Dublin", "Portmarnock"),
    _126    ("Dublin", "Sydney Parade"),
    _89     ("Dublin", "Navan Road Parkway"),
    _107    ("Dublin", "Sutton"),
    _127    ("Dublin", "Booterstown"),
    _96     ("Dublin", "Castleknock"),
    _112    ("Dublin", "Malahide"),
    _128    ("Dublin", "Blackrock"),
    _129    ("Dublin", "Seapoint"),
    _95     ("Dublin", "Coolmine"),
    _108    ("Dublin", "Howth"),
    _130    ("Dublin", "Salthill"),
    _1076   ("Dublin", "PARK WEST"),
    _976    ("Dublin", "Cherry Orchard"),
    _76     ("Dublin", "Cherry Orchard"),
    _131    ("Dublin", "Dun Laoghaire"),
    _132    ("Dublin", "Sandycove"),
    _1077   ("Dublin", "Clondalkin"),
    _77     ("Dublin", "Clondalkin"),
    _977    ("Dublin", "Clondalkin"),
    _94     ("Dublin", "Clonsilla"),
    _113    ("Dublin", "Donabate"),
    _133    ("Dublin", "Glenageary"),
    _87     ("Dublin", "Hansfield"),
    _134    ("Dublin", "Dalkey"),
    _975    ("Dublin", "Adamstown"),
    _75     ("Dublin", "Adamstown"),
    _85     ("Dublin", "Dunboyne"),
    _135    ("Dublin", "Killiney"),
    _114    ("Dublin", "Rush and Lusk"),
    _86     ("Dublin", "M3 Parkway"),
    _93     ("Dublin", "Leixlip (Confey)"),
    _136    ("Dublin", "Shankill"),
    _92     ("Dublin", "Leixlip (Louisa Bridge)"),
    _801    ("Dublin", "Woodbrook"),
    _1078   ("Dublin", "Hazelhatch"),
    _978    ("Dublin", "Hazelhatch"),
    _78     ("Dublin", "Hazelhatch"),
    _140    ("Dublin", "Bray"),
    _115    ("", "Skerries"),
    _91     ("", "Maynooth"),
    _116    ("", "Balbriggan"),
    _117    ("", "Gormanston"),
    _141    ("", "Greystones"),
    _90     ("", "Kilcock"),
    _79     ("", "Sallins"),
    _139    ("", "Kilcoole"),
    _119    ("", "Laytown"),
    _120    ("", "Drogheda"),
    _83     ("Station Yard", "Enfield"),
    _4      ("", "Newbridge"),
    _142    ("", "Wicklow"),
    _5      ("", "Curragh"),
    _143    ("", "Rathdrum"),
    _6      ("", "Kildare"),
    _1075   ("", "Adamstown"),
    _7      ("", "Monasterevin"),
    _144    ("", "Arklow"),
    _45     ("", "Athy"),
    _8      ("", "Portarlington"),
    _123    ("", "Dundalk"),
    _153    ("", "Mullingar"),
    _46     ("", "Carlow"),
    _145    ("", "Gorey"),
    _9      ("","Portlaoise"),
    _72     ("", "Tullamore"),
    _47     ("", "Muine Bheag"),
    _260    ("", "Newry"),
    _73     ("", "Clara"),
    _171    ("", "Edgeworthstown"),
    _147    ("", "Enniscorthy"),
    _48     ("", "Kilkenny"),
    _11     ("","Ballybrophy"),
    _172    ("", "Longford"),
    _156    ("", "Athlone"),
    _49     ("", "Thomastown"),
    _31     ("", "Roscrea"),
    _148    ("", "Wexford"),
    _242    ("", "Portadown"),
    _241    ("", "Lurgan"),
    _173    ("", "Drumod"),
    _58     ("", "Rosslare Strand"),
    _12     ("", "Templemore"),
    _60     ("", "Rosslare Harbour Europort"),
    _238    ("", "Lisburn"),
    _54     ("", "Wellingtonbridge"),
    _53     ("", "Ballycullane"),
    _32     ("", "Cloughjordan"),
    _56     ("", "Bridgetown"),
    _52     ("", "Campile"),
    _13     ("", "Thurles"),
    _163    ("", "Roscommon"),
    _157    ("", "Ballinasloe"),
    _50     ("", "Waterford"),
    _174    ("", "Carrick on Shannon"),
    _228    ("", "Belfast Central"),
    _44     ("", "Carrick on Suir"),
    _33     ("", "Nenagh"),
    _158    ("", "Woodlawn"),
    _43     ("", "Clonmel"),
    _175    ("", "Boyle"),
    _164    ("", "Castlerea"),
    _159    ("", "Attymon"),
    _42     ("", "Cahir"),
    _34     ("", "Birdhill"),
    _16     ("", "Limerick Junction"),
    _41     ("", "Tipperary"),
    _184    ("", "Craughwell"),
    _162    ("", "Athenry"),
    _35     ("", "Castleconnell"),
    _176    ("", "Ballymote"),
    _165    ("", "Ballyhaunis"),
    _177    ("", "Collooney"),
    _183    ("", "Ardrahan"),
    _182    ("", "Gort"),
    _180    ("", "Sligo"),
    _40     ("", "Limerick"),
    _161    ("", "Oranmore"),
    _185    ("", "Sixmilebridge"),
    _166    ("", "Claremorris"),
    _170    ("", "Galway"),
    _181    ("", "Ennis"),
    _19     ("", "Charleville"),
    _194    ("", "Manulla Junction"),
    _193    ("", "Foxford"),
    _168    ("", "Castlebar"),
    _68     ("", "Midleton"),
    _167    ("", "Ballina"),
    _67     ("", "Carrigtwohill"),
    _21     ("", "Mallow"),
    _380    ("", "Glounthaune"),
    _63     ("", "Fota"),
    _61     ("", "LittleIsland"),
    _64     ("", "Carrigaloe"),
    _66     ("", "Cobh"),
    _65     ("", "Rushbrooke"),
    _169    ("", "Westport"),
    _30     ("", "Cork"),
    _23     ("", "Banteer"),
    _24     ("", "Millstreet"),
    _25     ("", "Rathmore"),
    _27     ("", "Farranfore"),
    _28     ("", "Tralee"),
    _26     ("", "Killarney"),
    _1517   ("", "CENTRAL JUNCTION"),
    _1516   ("", "CITY JUNCTION"),
    _1518   ("", "DUNMURRAY"),
    _1519   ("", "MOIRA");

//    _109    ("Dublin", "Clontarf Road"),
//    _101    ("Dublin", "Killester"),
//    _99     ("Dublin", "Drumcondra"),
//    _102    ("Dublin", "Harmonstown"),
//    _100    ("Dublin", "Dublin Connolly"),
//    _84     ("Dublin", "Docklands"),
//    _103    ("Dublin", "Raheny"),
//    _124    ("Dublin", "Tara Street"),
//    _150    ("Dublin", "Dublin Pearse"),
//    _98     ("Dublin", "Broombridge"),
//    _110    ("Dublin", "Grand Canal Dock"),
//    _104    ("Dublin", "Kilbarrack"),
//    _125    ("Dublin", "Lansdowne Road"),
//    _105    ("Dublin", "Howth Junction"),
//    _1      ("Dublin", "Dublin Heuston"),
//    _188    ("Dublin", "Sandymount"),
//    _187    ("Dublin", "Clongriffin"),
//    _106    ("Dublin","Bayside"),
//    _97     ("Dublin", "Ashtown"),
//    _111    ("Dublin", "Portmarnock"),
//    _126    ("Dublin", "Sydney Parade"),
//    _89     ("Dublin", "Navan Road Parkway"),
//    _107    ("Dublin", "Sutton"),
//    _127    ("Dublin", "Booterstown"),
//    _96     ("Dublin", "Castleknock"),
//    _112    ("Dublin", "Malahide"),
//    _128    ("Dublin", "Blackrock"),
//    _129    ("Dublin", "Seapoint"),
//    _95     ("Dublin", "Coolmine"),
//    _108    ("Dublin", "Howth"),
//    _130    ("Dublin", "Salthill"),
//    _1076   ("Dublin", "PARK WEST"),
//    _976    ("Dublin", "Cherry Orchard"),
//    _76     ("Dublin", "Cherry Orchard"),
//    _131    ("Dublin", "Dun Laoghaire"),
//    _132    ("Dublin", "Sandycove"),
//    _1077   ("Dublin", "Clondalkin"),
//    _77     ("Dublin", "Clondalkin"),
//    _977    ("Dublin", "Clondalkin"),
//    _94     ("Dublin", "Clonsilla"),
//    _113    ("Dublin", "Donabate"),
//    _133    ("Dublin", "Glenageary"),
//    _87     ("Dublin", "Hansfield"),
//    _134    ("Dublin", "Dalkey"),
//    _975    ("Dublin", "Adamstown"),
//    _75     ("Dublin", "Adamstown"),
//    _85     ("Dublin", "Dunboyne"),
//    _135    ("Dublin", "Killiney"),
//    _114    ("Dublin", "Rush and Lusk"),
//    _86     ("Dublin", "M3 Parkway"),
//    _93     ("Dublin", "Leixlip (Confey)"),
//    _136    ("Dublin", "Shankill"),
//    _92     ("Dublin", "Leixlip (Louisa Bridge)"),
//    _801    ("Dublin", "Woodbrook"),
//    _1078   ("Dublin", "Hazelhatch"),
//    _978    ("Dublin", "Hazelhatch"),
//    _78     ("Dublin", "Hazelhatch"),
//    _140    ("Dublin", "Bray"),
//    _115    ("Skerries", "Skerries"),
//    _91     ("Maynooth", "Maynooth"),
//    _116    ("Balbriggan", "Balbriggan"),
//    _117    ("Gormanston", "Gormanston"),
//    _141    ("Greystones", "Greystones"),
//    _90     ("Kilcock", "Kilcock"),
//    _79     ("Sallins", "Sallins"),
//    _139    ("Kilcoole", "Kilcoole"),
//    _119    ("Laytown", "Laytown"),
//    _120    ("Drogheda", "Drogheda"),
//    _83     ("Station Yard", "Enfield"),
//    _4      ("Newbridge", "Newbridge"),
//    _142    ("Wicklow", "Wicklow"),
//    _5      ("Curragh", "Curragh"),
//    _143    ("Rathdrum", "Rathdrum"),
//    _6      ("Kildare", "Kildare"),
//    _1075   ("Adamstown", "Adamstown"),
//    _7      ("Monasterevin", "Monasterevin"),
//    _144    ("Arklow", "Arklow"),
//    _45     ("Athy", "Athy"),
//    _8      ("Portarlington", "Portarlington"),
//    _123    ("Dundalk", "Dundalk"),
//    _153    ("Mullingar", "Mullingar"),
//    _46     ("Carlow", "Carlow"),
//    _145    ("Gorey", "Gorey"),
//    _9      ("Portlaoise","Portlaoise"),
//    _72     ("Tullamore", "Tullamore"),
//    _47     ("Muine Bheag", "Muine Bheag"),
//    _260    ("Newry", "Newry"),
//    _73     ("Clara", "Clara"),
//    _171    ("Edgeworthstown", "Edgeworthstown"),
//    _147    ("Enniscorthy", "Enniscorthy"),
//    _48     ("Kilkenny", "Kilkenny"),
//    _11     ("Ballybrophy","Ballybrophy"),
//    _172    ("Longford", "Longford"),
//    _156    ("Athlone", "Athlone"),
//    _49     ("Thomastown", "Thomastown"),
//    _31     ("Roscrea", "Roscrea"),
//    _148    ("Wexford", "Wexford"),
//    _242    ("Portadown", "Portadown"),
//    _241    ("Lurgan", "Lurgan"),
//    _173    ("Drumod", "Drumod"),
//    _58     ("Rosslare", "Rosslare Strand"),
//    _12     ("Templemore", "Templemore"),
//    _60     ("Rosslare Harbour", "Rosslare Europort"),
//    _238    ("Lisburn", "Lisburn"),
//    _54     ("Wellingtonbridge", "Wellingtonbridge"),
//    _53     ("Ballycullane", "Ballycullane"),
//    _32     ("Cloughjordan", "Cloughjordan"),
//    _56     ("Bridgetown", "Bridgetown"),
//    _52     ("Campile", "Campile"),
//    _13     ("Thurles", "Thurles"),
//    _163    ("Roscommon", "Roscommon"),
//    _157    ("Ballinasloe", "Ballinasloe"),
//    _50     ("Waterford", "Waterford"),
//    _174    ("Carrick on Shannon", "Carrick on Shannon"),
//    _228    ("Belfast", "Belfast Central"),
//    _44     ("Carrick on Suir", "Carrick on Suir"),
//    _33     ("Nenagh", "Nenagh"),
//    _158    ("Woodlawn", "Woodlawn"),
//    _43     ("Clonmel", "Clonmel"),
//    _175    ("Boyle", "Boyle"),
//    _164    ("Castlerea", "Castlerea"),
//    _159    ("Attymon", "Attymon"),
//    _42     ("Cahir", "Cahir"),
//    _34     ("Birdhill", "Birdhill"),
//    _16     ("Limerick Junction", "Limerick Junction"),
//    _41     ("Tipperary", "Tipperary"),
//    _184    ("Craughwell", "Craughwell"),
//    _162    ("Athenry", "Athenry"),
//    _35     ("Castleconnell", "Castleconnell"),
//    _176    ("Ballymote", "Ballymote"),
//    _165    ("Ballyhaunis", "Ballyhaunis"),
//    _177    ("Collooney", "Collooney"),
//    _183    ("Ardrahan", "Ardrahan"),
//    _182    ("Gort", "Gort"),
//    _180    ("Sligo", "Sligo"),
//    _40     ("Limerick", "Limerick"),
//    _161    ("Oranmore", "Oranmore"),
//    _185    ("Sixmilebridge", "Sixmilebridge"),
//    _166    ("Claremorris", "Claremorris"),
//    _170    ("Galway", "Galway"),
//    _181    ("Ennis", "Ennis"),
//    _19     ("Charleville", "Charleville"),
//    _194    ("Manulla", "Manulla Junction"),
//    _193    ("Foxford", "Foxford"),
//    _168    ("Castlebar", "Castlebar"),
//    _68     ("Midleton", "Midleton"),
//    _167    ("Ballina", "Ballina"),
//    _67     ("Carrigtwohill", "Carrigtwohill"),
//    _21     ("Mallow", "Mallow"),
//    _380    ("Glounthaune", "Glounthaune"),
//    _63     ("Fota", "Fota"),
//    _61     ("LittleIsland", "LittleIsland"),
//    _64     ("Carrigaloe", "Carrigaloe"),
//    _66     ("Cobh", "Cobh"),
//    _65     ("Rushbrooke", "Rushbrooke"),
//    _169    ("Westport", "Westport"),
//    _30     ("Cork", "Cork"),
//    _23     ("Banteer", "Banteer"),
//    _24     ("Millstreet", "Millstreet"),
//    _25     ("Rathmore", "Rathmore"),
//    _27     ("Farranfore", "Farranfore"),
//    _28     ("Tralee", "Tralee"),
//    _26     ("Killarney", "Killarney"),
//    _1517   ("CENTRAL JUNCTION", "CENTRAL JUNCTION"),
//    _1516   ("CITY JUNCTION", "CITY JUNCTION"),
//    _1518   ("DUNMURRAY", "DUNMURRAY"),
//    _1519   ("MOIRA", "MOIRA");

    public static final String D = "Dublin";
    String city, name;
    Cities(String city, String name){
        this.city=city;
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public String getName() {
        return name;
    }
}

